[package]
name = "krypton-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
krypton-lang = { path = "../krypton-lang" }
krypton-vm = { path = "../krypton-vm", features = ["v1"] }
clap = "4.5.4"
