name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup update nightly
      - name: Install nightly versions of clippy & rustfmt
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt clippy
      - name: Check formatting
        run: cargo +nightly fmt -- --check
      - name: Check clippy
        run: "cargo +nightly clippy --all-targets --all-features -- 
                                                                -D warnings 
                                                                -W clippy::pedantic 
                                                                -W clippy::nursery 
                                                                -W clippy::cargo 
                                                                -W clippy:unwrap_used"

