name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup update${{ matrix.toolchain }} && rustup default${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check formatting
        run: cargo +nightly fmt -- --check
      - name: Check clippy
        run: cargo +nightly clippy -- -D warnings
