name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly
      - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt clippy
      - run: cargo +nightly fmt -- --check
      - run: cargo +nightly clippy --all-targets --all-features -- -D warnings -D clippy::dbg_macro

